export default Object.freeze({
    FOLLOW: 'FOLLOW',
    ONLINE_USER: 'ONLINE_USER',
    NOTIFICATION:'NOTIFICATION',
    ACCEPT_FOLLOW_REQUEST:'ACCEPT_FOLLOW_REQUEST',
    MESSAGE: "MESSAGE",
    CHATS: "CHATS",
    JOIN_GROUP_CHAT: "JOIN_GROUP_CHAT",
    TOKEN_EXPIRE:"TOKEN_EXPIRE"
})